### ISSUE TITLE
graphql-tools dependency

### ISSUE THREAD

**Issue by eug48** [apollographql/apollo-tracing-js#4]
Hi,

Currently apollo-tracing has a dependency on graphql-tools "^1.1.0" which seems to be causing TypeScript compile errors with the latest versions of apollo-server-core (1.1.0) and graphql-tools (2.20). It looks like graphql-tools 1.2.3 depends on `@types/graphql` 0.9.1 which is hoisted by yarn to apollo-server-core's node_modules, but it is not compatible with `@types/graphql` 0.11.4 which is used by graphql-tools 2.2.0... Thus passing the output of makeExecutableSchema to graphqlExpress leads to a type error.

If graphql-tools can be updated here that might fix this.

**Comment by martijnwalraven** [comment]
Ah, you're right, I'll update the dependency!

**Comment by eug48** [comment]
Thanks for the quick response!

However `apollo-server-core` still has `"apollo-tracing": "^0.0.7"` which is not picking up 0.0.8 as the ^ operator "allows changes that do not modify the left-most non-zero digit" ([npm doc](https://docs.npmjs.com/misc/semver))

**Comment by martijnwalraven** [comment]
Hmmm, I tried to update the dependency to `apollo-tracing` 0.0.8, but the tests fail because there is now an extra version of `graphql` installed. I think the reason for that is that `graphql-tools` 2.x relies on `apollo-link`, and that brings in `graphql` as a regular dependency (not a peer dependency). I'll have to discuss what we can do about that.

**Comment by martijnwalraven** [comment]
This should be fixed now.
